version: '3.8'

services:
  app:
    build: .
    container_name: order_app
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - app-network

  webserver:
    image: nginx:alpine
    container_name: order_nginx
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./nginx:/etc/nginx/conf.d
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: order_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: order_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
